## 1) Read file

In [100]:
import pandas as pd

In [101]:
data = pd.read_csv("Monthly-Demand.csv")

In [102]:
data.head(10)

        Month  Monthly Demand in Millions
0  01-07-1991                    3.526591
1  01-08-1991                    3.180891
2  01-09-1991                    3.252221
3  01-10-1991                    3.611003
4  01-11-1991                    3.565869
5  01-12-1991                    4.306371
6  01-01-1992                    5.088335
7  01-02-1992                    2.814520
8  01-03-1992                    2.985811
9  01-04-1992                    3.204780

In [103]:
data.columns

Index(['Month', 'Monthly Demand in Millions'], dtype='object')

## 2) Find Trend using 2*12 MA

In [104]:
no_of_rows = data.shape[0]

In [105]:
### Find 12 MA
# data["12MA"] = 0
window_12 = list(range(-5, 7, 1)) # [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6]

for y in range(5, no_of_rows-6):
    sum_12 = 0
    if (y+t > no_of_rows):
        break
    for t in window_12:
        sum_12 = sum_12 + data.loc[y+t, "Monthly Demand in Millions"]
    sum_12 = sum_12 / 12
    data.loc[y, "12MA"] = sum_12

In [106]:
## Find 2 MA
# data["2*12 MA/Trend"] = 0
window_2 = [-1, 0]

for y in range(6, no_of_rows-6):
    sum_2 = 0
    if (y+t > no_of_rows):
        break
    for t in window_2:
        sum_2 = sum_2 + data.loc[y+t, "12MA"]
    sum_2 = sum_2 / 2
    data.loc[y, "2*12 MA/Trend"] = sum_2

In [107]:
data.head(18)

         Month  Monthly Demand in Millions      12MA  2*12 MA/Trend
0   01-07-1991                    3.526591       NaN            NaN
1   01-08-1991                    3.180891       NaN            NaN
2   01-09-1991                    3.252221       NaN            NaN
3   01-10-1991                    3.611003       NaN            NaN
4   01-11-1991                    3.565869       NaN            NaN
5   01-12-1991                    4.306371  3.494541            NaN
6   01-01-1992                    5.088335  3.512146       3.503344
7   01-02-1992                    2.814520  3.543636       3.527891
8   01-03-1992                    2.985811  3.587385       3.565511
9   01-04-1992                    3.204780  3.613509       3.600447
10  01-05-1992                    3.127578  3.681897       3.647703
11  01-06-1992                    3.270523  3.807246       3.744571
12  01-07-1992                    3.737851  3.899223       3.853234
13  01-08-1992                    3.558776  3.952251       3.925737
14  01-09-1992                    3.777202  4.017793       3.985022
15  01-10-1992                    3.924490  4.061920       4.039856
16  01-11-1992                    4.386531  4.126738       4.094329
17  01-12-1992                    5.810549  4.191668       4.159203

## 3 a) Detrend data ( Additive)

In [108]:
data["Additive deTrend"] = data["Monthly Demand in Millions"] - data["2*12 MA/Trend"]

## 4 a) Find additive seasonal component

In [109]:
for mon in range(6, 18):
    no_of_years = 0
    sum_of_detrend = 0
    for step in range(0 , 199, 12):
        if mon+step >= 198:
            break
        sum_of_detrend = data.loc[mon + step,"Additive deTrend"]
        no_of_years = no_of_years + 1
    seasonality = sum_of_detrend / no_of_years
    
    for step in range(0 , 199, 12):
        if mon+step >= 198:
            break
#         print (mon + step, seasonality, data.loc[mon + step,"Additive deTrend"])
        data.loc[mon + step, "Additive Seasonality"] = seasonality

6 0.47277843229166683 1.5849914241666667
18 0.47277843229166683 1.9763279399999991
30 0.47277843229166683 1.825221872916667
42 0.47277843229166683 1.420883209166666
54 0.47277843229166683 2.254739328333333
66 0.47277843229166683 1.8217712729166662
78 0.47277843229166683 1.3754529104166657
90 0.47277843229166683 2.0861196587499986
102 0.47277843229166683 2.9512134858333336
114 0.47277843229166683 3.6437985141666687
126 0.47277843229166683 4.387896112916668
138 0.47277843229166683 4.102480605416666
150 0.47277843229166683 3.9523732716666675
162 0.47277843229166683 4.813376695833334
174 0.47277843229166683 6.092143749999998
186 0.47277843229166683 7.564454916666669
7 -0.25836989721354175 -0.7133712804166663
19 -0.25836989721354175 -0.8307628916666676
31 -0.25836989721354175 -1.1160345075000002
43 -0.25836989721354175 -1.1545669133333334
55 -0.25836989721354175 -1.0747252666666665
67 -0.25836989721354175 -1.465128490833334
79 -0.25836989721354175 -1.566867628333335
91 -0.25836989721354175 -1.989719554583333
103 -0.25836989721354175 -2.2567862254166657
115 -0.25836989721354175 -2.872207585
127 -0.25836989721354175 -2.9396471883333337
139 -0.25836989721354175 -2.945415137916667
151 -0.25836989721354175 -2.3298039533333323
163 -0.25836989721354175 -3.922227205833332
175 -0.25836989721354175 -4.9495724166666655
187 -0.25836989721354175 -4.133918355416668
8 -0.09933809635416657 -0.5796996895833333
20 -0.09933809635416657 -0.5857658866666662
32 -0.09933809635416657 -0.620912056249999
44 -0.09933809635416657 -0.45424091958333346
56 -0.09933809635416657 -0.9412160620833321
68 -0.09933809635416657 -1.0782376254166666
80 -0.09933809635416657 -1.023598042083334
92 -0.09933809635416657 -0.45451256624999914
104 -0.09933809635416657 -1.2187870629166664
116 -0.09933809635416657 -0.6816906112500014
128 -0.09933809635416657 -2.105056635000002
140 -0.09933809635416657 -1.959247936666669
152 -0.09933809635416657 -1.508551875416666
164 -0.09933809635416657 -2.847003708333334
176 -0.09933809635416657 -2.0020400416666675
188 -0.09933809635416657 -1.5894095416666651
9 -0.3308768694270834 -0.39566686250000016
21 -0.3308768694270834 -0.6893873954166656
33 -0.3308768694270834 -0.9908799304166669
45 -0.3308768694270834 -0.6263753170833324
57 -0.3308768694270834 -0.6770665724999985
69 -0.3308768694270834 -0.6519543145833326
81 -0.3308768694270834 -0.9433903208333323
93 -0.3308768694270834 -1.2982862324999997
105 -0.3308768694270834 -1.4688609933333314
117 -0.3308768694270834 -1.3112648558333344
129 -0.3308768694270834 -1.4478202716666662
141 -0.3308768694270834 -2.1889160479166687
153 -0.3308768694270834 -1.8248685595833312
165 -0.3308768694270834 -1.905563916666667
177 -0.3308768694270834 -3.3378545416666636
189 -0.3308768694270834 -5.294029910833334
10 -0.054171463541666576 -0.5201250850000001
22 -0.054171463541666576 -0.5787360170833327
34 -0.054171463541666576 -0.580313290416667
46 -0.054171463541666576 -0.30168155249999895
58 -0.054171463541666576 -0.21697775166666666
70 -0.054171463541666576 -0.5270594791666667
82 -0.054171463541666576 -0.6232071379166664
94 -0.054171463541666576 -0.7561271441666682
106 -0.054171463541666576 -0.717107466249999
118 -0.054171463541666576 -0.35075826541666544
130 -0.054171463541666576 -0.15082534208333342
142 -0.054171463541666576 -0.39637254583333537
154 -0.054171463541666576 -1.0107117600000013
166 -0.054171463541666576 -1.674761375000001
178 -0.054171463541666576 -0.1284115833333317
190 -0.054171463541666576 -0.8667434166666652
11 -0.08495312296875013 -0.4740484220833334
23 -0.08495312296875013 -0.520977945416667
35 -0.08495312296875013 -0.46303194333333497
47 -0.08495312296875013 -0.38926259583333245
59 -0.08495312296875013 -0.7110689412499989
71 -0.08495312296875013 -0.36453632
83 -0.08495312296875013 -0.37322488458333236
95 -0.08495312296875013 -0.6240124350000009
107 -0.08495312296875013 -0.6248927774999995
119 -0.08495312296875013 -1.3736258862499984
131 -0.08495312296875013 -1.3776942737499986
143 -0.08495312296875013 -0.8204351087500008
155 -0.08495312296875013 -1.2285491054166702
167 -0.08495312296875013 -0.8843029999999992
179 -0.08495312296875013 -1.9336662083333351
191 -0.08495312296875013 -1.359249967500002
12 -0.02350922973958358 -0.11538355458333394
24 -0.02350922973958358 -0.33463366625000024
36 -0.02350922973958358 -0.3161505774999993
48 -0.02350922973958358 -0.4196403333333327
60 -0.02350922973958358 0.028896291250000594
72 -0.02350922973958358 -0.05489336499999897
84 -0.02350922973958358 -0.02876053625000008
96 -0.02350922973958358 -0.20083503875000197
108 -0.02350922973958358 0.5434910599999991
120 -0.02350922973958358 -0.003797415833332707
132 -0.02350922973958358 0.4003845612500019
144 -0.02350922973958358 -0.08961801708333361
156 -0.02350922973958358 -0.09310365375000096
168 -0.02350922973958358 -0.9212483750000029
180 -0.02350922973958358 -1.572261375
192 -0.02350922973958358 -0.3761476758333373
13 0.09047549869791638 -0.36696118791666743
25 0.09047549869791638 -0.12675738541666703
37 0.09047549869791638 0.265480874583333
49 0.09047549869791638 0.07749135333333346
61 0.09047549869791638 -0.17418126749999896
73 0.09047549869791638 -0.4389051254166656
85 0.09047549869791638 -0.4977048783333329
97 0.09047549869791638 0.02122033458333128
109 0.09047549869791638 0.2455222991666659
121 0.09047549869791638 0.09488591875000019
133 0.09047549869791638 -0.30079852791666717
145 0.09047549869791638 -0.7084399341666678
157 0.09047549869791638 -0.1860820162500012
169 0.09047549869791638 0.6751357083333325
181 0.09047549869791638 -0.3061281666666673
193 0.09047549869791638 1.447607979166662
14 0.01922829776041657 -0.2078202500000006
26 0.01922829776041657 -0.12245445958333345
38 0.01922829776041657 0.08057839208333384
50 0.01922829776041657 -0.3356792479166666
62 0.01922829776041657 -0.03476941166666503
74 0.01922829776041657 0.04630837791666753
86 0.01922829776041657 0.2608784570833347
98 0.01922829776041657 0.062193447916666145
110 0.01922829776041657 -0.5864740274999996
122 0.01922829776041657 -0.9462001904166648
134 0.01922829776041657 0.2923964016666645
146 0.01922829776041657 -0.13700473958333426
158 0.01922829776041657 0.5592834591666627
170 0.01922829776041657 1.1193378333333328
182 0.01922829776041657 -2.6513332500000004
194 0.01922829776041657 0.3076527641666651
15 0.026621601197916345 -0.11536567500000094
27 0.026621601197916345 -0.1033821387499998
39 0.026621601197916345 0.12348409958333306
51 0.026621601197916345 0.2435812808333333
63 0.026621601197916345 0.2818363391666665
75 0.026621601197916345 0.5616624454166672
87 0.026621601197916345 0.15661387208333366
99 0.026621601197916345 0.06593212041666696
111 0.026621601197916345 1.0903613225000015
123 0.026621601197916345 1.0286682308333344
135 0.026621601197916345 0.951318832916666
147 0.026621601197916345 1.1442373029166646
159 0.026621601197916345 1.0204872162499985
171 0.026621601197916345 0.4385199166666638
183 0.026621601197916345 1.883918833333336
195 0.026621601197916345 0.4259456191666615
16 0.12841438036458275 0.2922021658333325
28 0.12841438036458275 0.2819295291666668
40 0.12841438036458275 0.5371660654166668
52 0.12841438036458275 0.1463599245833329
64 0.12841438036458275 0.06399204291666649
76 0.12841438036458275 0.09363541208333359
88 0.12841438036458275 0.4300482900000002
100 0.12841438036458275 0.637758980000001
112 0.12841438036458275 0.6061817179166695
124 0.12841438036458275 1.955511968333333
136 0.12841438036458275 0.6856590550000021
148 0.12841438036458275 -0.0724837566666654
160 0.12841438036458275 1.8702841695833357
172 0.12841438036458275 2.174022916666665
184 0.12841438036458275 3.8037177500000006
196 0.12841438036458275 2.054630085833324
17 0.16144284057291647 1.6513460383333323
29 0.16144284057291647 2.3167513658333334
41 0.16144284057291647 0.9188806637499995
53 0.16144284057291647 1.4147385237500005
65 0.16144284057291647 1.9685098266666667
77 0.16144284057291647 2.7347703699999997
89 0.16144284057291647 2.3238875116666655
101 0.16144284057291647 2.119056699583334
113 0.16144284057291647 1.2674586954166696
125 0.16144284057291647 1.1530846970833348
137 0.16144284057291647 2.465739971666668
149 0.16144284057291647 2.626292337083335
161 0.16144284057291647 2.9959048783333344
173 0.16144284057291647 2.70911933333333
185 0.16144284057291647 3.2454449166666635
197 0.16144284057291647 2.5830854491666635

In [110]:
data.head(10)

,Month,Monthly Demand in Millions,12MA,2*12 MA/Trend,Additive deTrend,Additive Seasonality
0,01-07-1991,3.526591,NaN,NaN,NaN,NaN
1,01-08-1991,3.180891,NaN,NaN,NaN,NaN
2,01-09-1991,3.252221,NaN,NaN,NaN,NaN
3,01-10-1991,3.611003,NaN,NaN,NaN,NaN
4,01-11-1991,3.565869,NaN,NaN,NaN,NaN
5,01-12-1991,4.306371,3.494541,NaN,NaN,NaN
6,01-01-1992,5.088335,3.512146,3.503344,1.584991,0.472778
7,01-02-1992,2.814520,3.543636,3.527891,-0.713371,-0.258370
8,01-03-1992,2.985811,3.587385,3.565511,-0.579700,-0.099338
9,01-04-1992,3.204780,3.613509,3.600447,-0.395667,-0.330877

## 5 a) Find additve residual component

## 3 a) Detrend data ( Multiplicative)

## 4 a) Find multiplicative seasonal component

## 5 a) Find multiplicative residual component